### ISSUE TITLE
showing error on Wordpress 5.2

### ISSUE THREAD

**Issue by rahulgenesis91** [sendyit/woocommerce#1]
Warning: Declaration of Sendy_Shipping_Method::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) in public_html/wp-content/plugins/sendy-api/sendy-api.php on line 47

also showing another warning

Warning: A non-numeric value encountered in public_html/wp-content/plugins/sendy-api/sendy-api.php on line 186

**Comment by thegeektets** [comment]
isssue resolved
